spring:
  config:
    import: optional:application-secret.yml

  application:
    name: readcovery

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:mysql://localhost:3306/readcovery?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

kakao:
  api-key: ${kakao.api-key}

server:
  port: 8080